### ISSUE TITLE
package mingw-w64-x86_64-clang-4.0.0-1 lacks signature.

### ISSUE THREAD

**Issue by TurnOffNOD** [Alexpux/MSYS2-pacman#42] opened 2017-05-22 07:12 UTC
When I pacman -Syuu today, pacman reports : 

`error: mingw-w64-x86_64-clang: missing required signature
error: failed to commit transaction (invalid or corrupted package)`
`Errors occurred, no packages were upgraded.`

I consult the repository, and find that the package
http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-clang-4.0.0-1-any.pkg.tar.xz
exists , but the package's signature (http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-clang-4.0.0-1-any.pkg.tar.xz.sig) is missing.

Please check it.

**Comment by myfreeer** [comment] 2017-05-23 12:42
Duplicate of https://github.com/Alexpux/MINGW-packages/issues/2477

**Comment by elieux** [comment] 2017-05-24 15:37
Resolved, can be closed.

**Closed as completed** 2017-06-06 16:52 UTC
